<a href="https://colab.research.google.com/github/arosales23/CIS-3902-AI-ML-ARA/blob/main/Autoviz_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Autoviz
<p><a href="https://github.com/AutoViML/AutoViz">AutoViz documentation in Github</a></p>

Name: Alan Rosales

Date: 3/23/26

Class: CIS3902

In [ ]:
!pip install autoviz

Requirement already satisfied: autoviz in /usr/local/lib/python3.12/dist-packages (0.1.905)
Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.0.2)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.9.6)
Requirement already satisfied: emoji in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.15.0)
Requirement already satisfied: pyamg in /usr/local/lib/python3.12/dist-packages (from autoviz) (5.3.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.14.6)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from autoviz) (3.9.1)
Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.19.0)
Requirement already satisfied: xgboost<1.7,>=0.82 in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.6.2)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from autoviz) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from autoviz) (4.15.0)
Requirement already satisfied: pandas-dq>=1.29 in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.29)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.0.2)
Requirement already satisfied: hvplot>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.12.2)
Requirement already satisfied: holoviews>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.22.1)
Requirement already satisfied: panel>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (1.8.10)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from autoviz) (2.2.2)
Requirement already satisfied: matplotlib>3.7.4 in /usr/local/lib/python3.12/dist-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in /usr/local/lib/python3.12/dist-packages (from autoviz) (0.13.2)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (3.8.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (3.1.0)
Requirement already satisfied: narwhals>=2 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (2.18.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (26.0)
Requirement already satisfied: param<3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.12/dist-packages (from holoviews>=1.16.0->autoviz) (3.0.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>3.7.4->autoviz) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->autoviz) (2025.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (6.3.0)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (2.1.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (3.10.2)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (0.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from panel>=1.4.0->autoviz) (4.67.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->autoviz) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->autoviz) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->autoviz) (3.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->autoviz) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->autoviz) (2025.11.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->autoviz) (1.0.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2025.11.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->autoviz) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: uc-micro-py in /usr/local/lib/python3.12/dist-packages (from linkify-it-py->panel>=1.4.0->autoviz) (2.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->panel>=1.4.0->autoviz) (2026.2.25)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.3)

#Seaborn
<p>Seaborn provides several built-in datasets, including "iris", "penguins", "flights", "titanic", "tips", "diamonds", and "exercise", which can be loaded using the seaborn.load_dataset() function. </p>

In [ ]:
import seaborn as sns

In [ ]:
df=sns.load_dataset('tips') #tips is available in seaborn

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
from autoviz.AutoViz_Class import AutoViz_Class

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)

AV=autoViz_clss()

In [ ]:
AV = AutoViz_Class()
dft = AV.AutoViz(
    "", #this is for a filename if you aren't using a dataframe
    sep=",", #separator in the file, generally comma
    depVar="size", #this is for a target variable name if you have one that you are using in prediction
    dfte=df, #dataframe that has been used for the file that has been input
    header=0, #header row which is typically the first
    verbose=1, #0 minimal charts,  1 is more charts, 2 is for saving locally without display
    lowess=True, #creates regression line with dependent variable for all continuous variables
    chart_format="bokeh",
    max_rows_analyzed=150000,
    max_cols_analyzed=30,
    save_plot_dir=None
)

Shape of your Data Set loaded: (244, 7)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  2
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  4
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    6 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Multi_Classification problem #####################

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

Row
    [0] WidgetBox
        [0] Select(name='x', options=['size'], value='size')
        [1] Select(name='y', options=['total_bill', 'tip'], value='total_bill')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Row
    [0] WidgetBox
        [0] Select(name='X-Axis', options=['total_bill', 'tip'], value='total_bill')
        [1] Select(name='Y-Axis', options=['total_bill', 'tip'], value='tip')
        [2] Select(name='Color', options=['None', 'size'], value='None')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(options=[np.str_('sex'), ...], value=np.str_('sex'))

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(options=[np.str_('total_bill'), ...], value=np.str_('total_bill'))

KDE plot is erroring due to problems with DynamicMaps. Hence it is skipped

HoloViews(Layout)

No date vars could be found in data set

HoloViews(Overlay, height=500, sizing_mode='fixed', width=600)

Row
    [0] WidgetBox
        [0] Select(name='X-Axis', options=['sex', 'smoker', ...], value='sex')
        [1] Select(name='Y-Axis', options=['total_bill', 'tip'], value='total_bill')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Time to run AutoViz (in seconds) = 14

#from AutoViz documentation in Github
<p
Arguments for AV.AutoViz() method:<br>

filename: Use an empty string ("") if there's no associated filename and you want to use a dataframe. In that case, using the dfte argument for the dataframe. Otherwise provide a filename and leave dfte argument with an empty string. Only one of them can be used.<br>
sep: File separator (comma, semi-colon, tab, or any column-separating value) if you use a filename above.<br>
depVar: Target variable in your dataset; set it as an empty string if not applicable.<br>
dfte: name of the pandas dataframe for plotting charts; leave it as empty string if using a filename.<br>
header: set the row number of the header row in your file (0 for the first row). Otherwise leave it as 0.<br>
verbose: 0 for minimal info and charts, 1 for more info and charts, or 2 for saving charts locally without display.<br>
lowess: Use regression lines for each pair of continuous variables against the target variable in small datasets; avoid using for large datasets (>100,000 rows).<br>
chart_format: 'svg', 'png', 'jpg', 'bokeh', 'server', or 'html' for displaying or saving charts in various formats, depending on the verbose option.<br>
max_rows_analyzed: Limit the max number of rows to use for visualization when dealing with very large datasets (millions of rows). A statistically valid sample will be used by autoviz. Default is 150000 rows.<br>
max_cols_analyzed: Limit the number of continuous variables to be analyzed. Defaul is 30 columns.<br>
save_plot_dir: Directory for saving plots. Default is None, which saves plots under the current directory in a subfolder named AutoViz_Plots. If the save_plot_dir doesn't exist, it will be created.</p>

In [ ]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

# 'Attention' Dataset

In [ ]:
dfpen=sns.load_dataset('titanic')

In [ ]:
dfpen.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
AV2 = AutoViz_Class()
dft = AV.AutoViz(
    "", #this is for a filename if you aren't using a dataframe
    sep=",", #separator in the file, generally comma
    depVar="survived", #this is for a target variable name if you have one that you are using in prediction
    dfte=dfpen, #dataframe that has been used for the file that has been input
    header=0, #header row which is typically the first
    verbose=1, #0 minimal charts,  1 is more charts, 2 is for saving locally without display
    lowess=True, #creates regression line with dependent variable for all continuous variables
    chart_format="bokeh",
    max_rows_analyzed=150000,
    max_cols_analyzed=30,
    save_plot_dir=None
)

Shape of your Data Set loaded: (891, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  2
    Number of Integer-Categorical Columns =  3
    Number of String-Categorical Columns =  3
    Number of Factor-Categorical Columns =  2
    Number of String-Boolean Columns =  4
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

Row
    [0] WidgetBox
        [0] Select(name='x', options=['survived'], value='survived')
        [1] Select(name='y', options=['age', 'fare'], value='age')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Row
    [0] WidgetBox
        [0] Select(name='X-Axis', options=['age', 'fare'], value='age')
        [1] Select(name='Y-Axis', options=['age', 'fare'], value='fare')
        [2] Select(name='Color', options=['None', 'survived'], value='None')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(options=[np.str_('embarked'), ...], value=np.str_('embarked'))

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(options=[np.str_('age'), ...], value=np.str_('age'))

KDE plot is erroring due to problems with DynamicMaps. Hence it is skipped

HoloViews(Layout)

No date vars could be found in data set

HoloViews(Overlay, height=500, sizing_mode='fixed', width=600)

Row
    [0] WidgetBox
        [0] Select(name='X-Axis', options=['embarked', 'who', ...], value='embarked')
        [1] Select(name='Y-Axis', options=['age', 'fare'], value='age')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Time to run AutoViz (in seconds) = 3

The Titanic dataset describes the people that survived or died (i.e., Age, Sex, Fare, Class, etc.). Using AutoViz, the dataset can be further analyzed to see the details of every person whether they died on the ship or not. Additionally, using the graphs, it can be seen whether or not there is a relationship between deaths or non-deaths and every other variable that describes them.